/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesQueueRouteImport } from './routes/sales.queue'
import { Route as SalesPipelineRouteImport } from './routes/sales.pipeline'
import { Route as CallCentreSubmissionsRouteImport } from './routes/call-centre.submissions'
import { Route as CallCentreNewLeadRouteImport } from './routes/call-centre.new-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQueueRoute = SalesQueueRouteImport.update({
  id: '/sales/queue',
  path: '/sales/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPipelineRoute = SalesPipelineRouteImport.update({
  id: '/sales/pipeline',
  path: '/sales/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCentreSubmissionsRoute = CallCentreSubmissionsRouteImport.update({
  id: '/call-centre/submissions',
  path: '/call-centre/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCentreNewLeadRoute = CallCentreNewLeadRouteImport.update({
  id: '/call-centre/new-lead',
  path: '/call-centre/new-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/call-centre/new-lead': typeof CallCentreNewLeadRoute
  '/call-centre/submissions': typeof CallCentreSubmissionsRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/queue': typeof SalesQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/call-centre/new-lead': typeof CallCentreNewLeadRoute
  '/call-centre/submissions': typeof CallCentreSubmissionsRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/queue': typeof SalesQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/call-centre/new-lead': typeof CallCentreNewLeadRoute
  '/call-centre/submissions': typeof CallCentreSubmissionsRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/queue': typeof SalesQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/call-centre/new-lead'
    | '/call-centre/submissions'
    | '/sales/pipeline'
    | '/sales/queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/call-centre/new-lead'
    | '/call-centre/submissions'
    | '/sales/pipeline'
    | '/sales/queue'
  id:
    | '__root__'
    | '/'
    | '/call-centre/new-lead'
    | '/call-centre/submissions'
    | '/sales/pipeline'
    | '/sales/queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallCentreNewLeadRoute: typeof CallCentreNewLeadRoute
  CallCentreSubmissionsRoute: typeof CallCentreSubmissionsRoute
  SalesPipelineRoute: typeof SalesPipelineRoute
  SalesQueueRoute: typeof SalesQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/queue': {
      id: '/sales/queue'
      path: '/sales/queue'
      fullPath: '/sales/queue'
      preLoaderRoute: typeof SalesQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/pipeline': {
      id: '/sales/pipeline'
      path: '/sales/pipeline'
      fullPath: '/sales/pipeline'
      preLoaderRoute: typeof SalesPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-centre/submissions': {
      id: '/call-centre/submissions'
      path: '/call-centre/submissions'
      fullPath: '/call-centre/submissions'
      preLoaderRoute: typeof CallCentreSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-centre/new-lead': {
      id: '/call-centre/new-lead'
      path: '/call-centre/new-lead'
      fullPath: '/call-centre/new-lead'
      preLoaderRoute: typeof CallCentreNewLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallCentreNewLeadRoute: CallCentreNewLeadRoute,
  CallCentreSubmissionsRoute: CallCentreSubmissionsRoute,
  SalesPipelineRoute: SalesPipelineRoute,
  SalesQueueRoute: SalesQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
