/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesQueueRouteImport } from './routes/sales.queue'
import { Route as SalesPipelineRouteImport } from './routes/sales.pipeline'
import { Route as SalesLedgerRouteImport } from './routes/sales.ledger'
import { Route as SalesDashboardRouteImport } from './routes/sales.dashboard'
import { Route as ManagementWorkloadRouteImport } from './routes/management.workload'
import { Route as ManagementSalvageRouteImport } from './routes/management.salvage'
import { Route as ManagementRecallRouteImport } from './routes/management.recall'
import { Route as ManagementReactivationRouteImport } from './routes/management.reactivation'
import { Route as ManagementKpiRouteImport } from './routes/management.kpi'
import { Route as ManagementHermesRouteImport } from './routes/management.hermes'
import { Route as ManagementChurnRouteImport } from './routes/management.churn'
import { Route as ManagementAuditRouteImport } from './routes/management.audit'
import { Route as CallCentreAssistantRouteImport } from './routes/call-centre.assistant'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiPublicSlackEventsRouteImport } from './routes/api/public/slack.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesQueueRoute = SalesQueueRouteImport.update({
  id: '/sales/queue',
  path: '/sales/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesPipelineRoute = SalesPipelineRouteImport.update({
  id: '/sales/pipeline',
  path: '/sales/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLedgerRoute = SalesLedgerRouteImport.update({
  id: '/sales/ledger',
  path: '/sales/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDashboardRoute = SalesDashboardRouteImport.update({
  id: '/sales/dashboard',
  path: '/sales/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementWorkloadRoute = ManagementWorkloadRouteImport.update({
  id: '/management/workload',
  path: '/management/workload',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementSalvageRoute = ManagementSalvageRouteImport.update({
  id: '/management/salvage',
  path: '/management/salvage',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRecallRoute = ManagementRecallRouteImport.update({
  id: '/management/recall',
  path: '/management/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementReactivationRoute = ManagementReactivationRouteImport.update({
  id: '/management/reactivation',
  path: '/management/reactivation',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementKpiRoute = ManagementKpiRouteImport.update({
  id: '/management/kpi',
  path: '/management/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementHermesRoute = ManagementHermesRouteImport.update({
  id: '/management/hermes',
  path: '/management/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementChurnRoute = ManagementChurnRouteImport.update({
  id: '/management/churn',
  path: '/management/churn',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementAuditRoute = ManagementAuditRouteImport.update({
  id: '/management/audit',
  path: '/management/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCentreAssistantRoute = CallCentreAssistantRouteImport.update({
  id: '/call-centre/assistant',
  path: '/call-centre/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSlackEventsRoute = ApiPublicSlackEventsRouteImport.update({
  id: '/api/public/slack/events',
  path: '/api/public/slack/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/tts': typeof ApiTtsRoute
  '/call-centre/assistant': typeof CallCentreAssistantRoute
  '/management/audit': typeof ManagementAuditRoute
  '/management/churn': typeof ManagementChurnRoute
  '/management/hermes': typeof ManagementHermesRoute
  '/management/kpi': typeof ManagementKpiRoute
  '/management/reactivation': typeof ManagementReactivationRoute
  '/management/recall': typeof ManagementRecallRoute
  '/management/salvage': typeof ManagementSalvageRoute
  '/management/workload': typeof ManagementWorkloadRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/ledger': typeof SalesLedgerRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/queue': typeof SalesQueueRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/tts': typeof ApiTtsRoute
  '/call-centre/assistant': typeof CallCentreAssistantRoute
  '/management/audit': typeof ManagementAuditRoute
  '/management/churn': typeof ManagementChurnRoute
  '/management/hermes': typeof ManagementHermesRoute
  '/management/kpi': typeof ManagementKpiRoute
  '/management/reactivation': typeof ManagementReactivationRoute
  '/management/recall': typeof ManagementRecallRoute
  '/management/salvage': typeof ManagementSalvageRoute
  '/management/workload': typeof ManagementWorkloadRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/ledger': typeof SalesLedgerRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/queue': typeof SalesQueueRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/tts': typeof ApiTtsRoute
  '/call-centre/assistant': typeof CallCentreAssistantRoute
  '/management/audit': typeof ManagementAuditRoute
  '/management/churn': typeof ManagementChurnRoute
  '/management/hermes': typeof ManagementHermesRoute
  '/management/kpi': typeof ManagementKpiRoute
  '/management/reactivation': typeof ManagementReactivationRoute
  '/management/recall': typeof ManagementRecallRoute
  '/management/salvage': typeof ManagementSalvageRoute
  '/management/workload': typeof ManagementWorkloadRoute
  '/sales/dashboard': typeof SalesDashboardRoute
  '/sales/ledger': typeof SalesLedgerRoute
  '/sales/pipeline': typeof SalesPipelineRoute
  '/sales/queue': typeof SalesQueueRoute
  '/api/public/slack/events': typeof ApiPublicSlackEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/tts'
    | '/call-centre/assistant'
    | '/management/audit'
    | '/management/churn'
    | '/management/hermes'
    | '/management/kpi'
    | '/management/reactivation'
    | '/management/recall'
    | '/management/salvage'
    | '/management/workload'
    | '/sales/dashboard'
    | '/sales/ledger'
    | '/sales/pipeline'
    | '/sales/queue'
    | '/api/public/slack/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/tts'
    | '/call-centre/assistant'
    | '/management/audit'
    | '/management/churn'
    | '/management/hermes'
    | '/management/kpi'
    | '/management/reactivation'
    | '/management/recall'
    | '/management/salvage'
    | '/management/workload'
    | '/sales/dashboard'
    | '/sales/ledger'
    | '/sales/pipeline'
    | '/sales/queue'
    | '/api/public/slack/events'
  id:
    | '__root__'
    | '/'
    | '/api/tts'
    | '/call-centre/assistant'
    | '/management/audit'
    | '/management/churn'
    | '/management/hermes'
    | '/management/kpi'
    | '/management/reactivation'
    | '/management/recall'
    | '/management/salvage'
    | '/management/workload'
    | '/sales/dashboard'
    | '/sales/ledger'
    | '/sales/pipeline'
    | '/sales/queue'
    | '/api/public/slack/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTtsRoute: typeof ApiTtsRoute
  CallCentreAssistantRoute: typeof CallCentreAssistantRoute
  ManagementAuditRoute: typeof ManagementAuditRoute
  ManagementChurnRoute: typeof ManagementChurnRoute
  ManagementHermesRoute: typeof ManagementHermesRoute
  ManagementKpiRoute: typeof ManagementKpiRoute
  ManagementReactivationRoute: typeof ManagementReactivationRoute
  ManagementRecallRoute: typeof ManagementRecallRoute
  ManagementSalvageRoute: typeof ManagementSalvageRoute
  ManagementWorkloadRoute: typeof ManagementWorkloadRoute
  SalesDashboardRoute: typeof SalesDashboardRoute
  SalesLedgerRoute: typeof SalesLedgerRoute
  SalesPipelineRoute: typeof SalesPipelineRoute
  SalesQueueRoute: typeof SalesQueueRoute
  ApiPublicSlackEventsRoute: typeof ApiPublicSlackEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/queue': {
      id: '/sales/queue'
      path: '/sales/queue'
      fullPath: '/sales/queue'
      preLoaderRoute: typeof SalesQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/pipeline': {
      id: '/sales/pipeline'
      path: '/sales/pipeline'
      fullPath: '/sales/pipeline'
      preLoaderRoute: typeof SalesPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/ledger': {
      id: '/sales/ledger'
      path: '/sales/ledger'
      fullPath: '/sales/ledger'
      preLoaderRoute: typeof SalesLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/dashboard': {
      id: '/sales/dashboard'
      path: '/sales/dashboard'
      fullPath: '/sales/dashboard'
      preLoaderRoute: typeof SalesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/workload': {
      id: '/management/workload'
      path: '/management/workload'
      fullPath: '/management/workload'
      preLoaderRoute: typeof ManagementWorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/salvage': {
      id: '/management/salvage'
      path: '/management/salvage'
      fullPath: '/management/salvage'
      preLoaderRoute: typeof ManagementSalvageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/recall': {
      id: '/management/recall'
      path: '/management/recall'
      fullPath: '/management/recall'
      preLoaderRoute: typeof ManagementRecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/reactivation': {
      id: '/management/reactivation'
      path: '/management/reactivation'
      fullPath: '/management/reactivation'
      preLoaderRoute: typeof ManagementReactivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/kpi': {
      id: '/management/kpi'
      path: '/management/kpi'
      fullPath: '/management/kpi'
      preLoaderRoute: typeof ManagementKpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/hermes': {
      id: '/management/hermes'
      path: '/management/hermes'
      fullPath: '/management/hermes'
      preLoaderRoute: typeof ManagementHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/churn': {
      id: '/management/churn'
      path: '/management/churn'
      fullPath: '/management/churn'
      preLoaderRoute: typeof ManagementChurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/audit': {
      id: '/management/audit'
      path: '/management/audit'
      fullPath: '/management/audit'
      preLoaderRoute: typeof ManagementAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-centre/assistant': {
      id: '/call-centre/assistant'
      path: '/call-centre/assistant'
      fullPath: '/call-centre/assistant'
      preLoaderRoute: typeof CallCentreAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/slack/events': {
      id: '/api/public/slack/events'
      path: '/api/public/slack/events'
      fullPath: '/api/public/slack/events'
      preLoaderRoute: typeof ApiPublicSlackEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTtsRoute: ApiTtsRoute,
  CallCentreAssistantRoute: CallCentreAssistantRoute,
  ManagementAuditRoute: ManagementAuditRoute,
  ManagementChurnRoute: ManagementChurnRoute,
  ManagementHermesRoute: ManagementHermesRoute,
  ManagementKpiRoute: ManagementKpiRoute,
  ManagementReactivationRoute: ManagementReactivationRoute,
  ManagementRecallRoute: ManagementRecallRoute,
  ManagementSalvageRoute: ManagementSalvageRoute,
  ManagementWorkloadRoute: ManagementWorkloadRoute,
  SalesDashboardRoute: SalesDashboardRoute,
  SalesLedgerRoute: SalesLedgerRoute,
  SalesPipelineRoute: SalesPipelineRoute,
  SalesQueueRoute: SalesQueueRoute,
  ApiPublicSlackEventsRoute: ApiPublicSlackEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
